### ISSUE TITLE
CurrentlyReading , FinishedReading , Wish List State is not preserved on refresh

### ISSUE THREAD

**Issue by ellispinsky** [agiledev-students-spring2024/4-final-project-readtrack#119]
This book is on my current reads , but that is not toggled. We need to ensure this is preserved on refresh, 

<img width="500" alt="Screenshot 2024-04-17 at 3 14 59 PM" src="https://github.com/agiledev-students-spring2024/4-final-project-readtrack/assets/48781372/601f41e1-cab4-4fb4-9a23-75f2f2eba9aa">

**Comment by jeffreysaeteros** [comment]
check pr #124
